name: Firebase Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: functions/package-lock.json

      - name: Install Dependencies
        run: npm ci -C functions

      - name: Setup Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
        env:
          CACHE_VERSION: v1
        continue-on-error: true

      - name: Run tests
        run: npm run test -C functions

      - name: Deploy to Firebase
        if: ${{ success() }}
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
